
version: '3.7'
volumes:
  prometheus_data: {}
  # grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./services/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    network_mode: host

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo-local.yaml"]
    volumes:
      - ./services/tempo/tempo-local.yaml:/etc/tempo-local.yaml
    ports:
    - "6832:6832/udp"
    - 3200:3200

  tempo-query:
    image: grafana/tempo-query:latest
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
    - ./services/tempo-query/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
    - "16686:16686"  # jaeger-ui
    depends_on:
    - tempo
  grafana:
    image: grafana/grafana
    user: "472"
    # depends_on:
    #   - prometheus
    ports:
      - 9000:9000
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./services/grafana/provisioning/:/etc/grafana/provisioning/
      - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - ./services/grafana/config.monitoring
    restart: always
    network_mode: host

  # jaeger:
  #   image: jaegertracing/all-in-one:1.40
  #   environment:
  #     COLLECTOR_ZIPKIN_HOST_PORT: ':9411'
  #     COLLECTOR_OTLP_ENABLED: "false"
  #   ports:
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "4317:4317"
  #     - "4318:4318"
  #     - "14250:14250"
  #     - "14268:14268"
  #     - "14269:14269"
  #     - "9411:9411"
    # network_mode: host
# volumes:
#     prometheus_data: {}
