global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-project'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'application'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:3000']
