name: Base tet

on:
  workflow_call:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Nodejs
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Build
        run: npm ci

      - name: Test
        run: npm test

      # - uses: IgnusG/jest-report-action@v2.3.3
      #   if: always()
      #   with:
      #     access-token: ${{ secrets.GITHUB_TOKEN }}
      #     check-name: Jest test with node-version ${{ matrix.version }}
