name: Example

on:
  push:
    branches:
      - '*'
    # paths:
    #   - 'src/**.ts'
jobs:
  test:
    uses: devmasx/actions-reusing-workflows/nodejs/build-test.yml@main
    with:
      node-version: 16
