name: Example

on:
  push:
    branches:
      - '*'
    # paths:
    #   - 'src/**.ts'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat ./.github/workflows/base-test.yml
      - uses: ./.github/workflows/base-test.yml
