name: Example

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**.ts'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Build
        run: npm ci

      # - run: cat $GITHUB_EVENT_PATH
      # - run: echo $GITHUB_REF
      # - run: echo $GITHUB_PATH
      # - run: echo $GITHUB_HEAD_REF
      # - run: echo $GITHUB_ACTION_PATH

      - name: Detect path
        run: git diff-tree -r --name-only $GITHUB_REF $GITHUB_BASE_REF

      - name: Test
        run: npm test -- src/app.controller.spec.ts

      # - uses: IgnusG/jest-report-action@v2.3.3
      #   if: always()
      #   with:
      #     access-token: ${{ secrets.GITHUB_TOKEN }}
      #     check-name: Jest test with node-version ${{ matrix.version }}
